import {ArrowRight,BookOpen,ShieldCheck,ArrowUpRight} from 'lucide-react';
import {SiteLink as Link} from '@/components/site/site-link';
import {seo} from '@/lib/seo';
import {guides,guideTopics} from '@/lib/guides';
import {ResourceLayout,ResourceCTA} from '@/components/site/resource-layout';
export const metadata=seo('Guides & Articles — Practical Tool Know-how','Practical Tool Fera guides to file processing, browser privacy and common utility workflows. Explore the published guide and instructions for each tool.','/blog/');
export default function Blog(){const featured=guides[0];return <ResourceLayout name="Guides & articles" path="/blog/" eyebrow="A LITTLE EXTRA CLARITY" title="Useful tools. Useful know-how." description="Understand the workflow, choose the right settings and know what to check in the result. Practical reading for everyday digital tasks.">
 <section className="guide-feature" aria-labelledby="featured-guide"><div className="guide-feature-art" aria-hidden="true"><div className="guide-document"><BookOpen/><i/><i/><i/><span><ShieldCheck/></span></div><span className="guide-art-label">ON YOUR DEVICE</span></div><div className="guide-feature-copy"><span className="eyebrow">FEATURED GUIDE · {featured.topic}</span><h2 id="featured-guide">{featured.title}</h2><p>{featured.description}</p><Link className="primary-button" href={featured.href}>Read the guide<ArrowRight size={17} aria-hidden="true"/></Link></div></section>
 <section className="resource-section" aria-labelledby="guide-topics"><div className="resource-section-heading"><span className="eyebrow">EXPLORE BY TASK</span><h2 id="guide-topics">Helpful context, right where you work.</h2><p>The guide collection is just getting started. For task-specific instructions, open a tool below: its page explains how to use it and what its limits are.</p></div><nav className="guide-topics" aria-label="Collections with tool instructions">{guideTopics.map(topic=><Link href={topic.href} key={topic.href}><h3>{topic.name}<ArrowUpRight size={17} aria-hidden="true"/></h3><p>{topic.text}</p><span>Tool instructions</span></Link>)}</nav></section>
 <aside className="resource-editorial-note"><BookOpen size={21} aria-hidden="true"/><p>One published guide, with more room to grow. Browse the current article above or use the instructions on individual tool pages. Topic cards lead to tool collections.</p></aside><ResourceCTA title="Put the know-how to work." description="Go from a useful explanation to the tool you need, with the same clear workflow."/>
 </ResourceLayout>}
