'use client';
import {useState,useId} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {percentage,weightedAverage,journeyFuelCost} from '@/tools/math';
import {currencies,fuelRegions} from '@/tools/fuel-options';
function Field({label,value,onChange,min,max}:{label:string;value:string;onChange:(v:string)=>void;min?:number;max?:number}){const id=useId();return <div><label className="field-label" htmlFor={id}>{label}</label><input className="field-input" type="number" id={id} value={value} onChange={e=>onChange(e.target.value)} step="any" min={min} max={max}/></div>}
const number=(v:string)=>v.trim()===''?NaN:Number(v);const format=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:4});
const currencyNames=new Intl.DisplayNames(['en'],{type:'currency'});
export default function MathTools({kind}:{kind:string}){return kind==='percentage'?<Percentage/>:kind==='fuel'?<Fuel/>:<GPA cumulative={kind==='cgpa'}/>}
function Percentage(){
 const[a,A]=useState('15');const[b,B]=useState('200');const[mode,M]=useState<'of'|'ratio'>('of');let value=0,error='';
 try{value=percentage(number(a),number(b),mode);if(!Number.isFinite(value))error='These values are too large to calculate.'}catch(e){error=(e as Error).message}
 const content=<><div className="input-grid"><Field label={mode==='of'?'Percentage (A %)':'Value (A)'} value={a} onChange={A}/><Field label={mode==='of'?'Number (B)':'Total (B)'} value={b} onChange={B}/></div><div className="result-panel"><output aria-live="polite" aria-atomic="true"><span className="result-label">Your result</span>{error?<p className="error-message">{error}</p>:<><strong className="result-value">{format(value)}{mode==='ratio'?'%':''}</strong><p className="result-detail">{mode==='of'?`${a} ÷ 100 × ${b}`:`${a} ÷ ${b} × 100`}</p></>}</output></div></>;
 return <Tabs className="calc-tabs" value={mode} onValueChange={v=>M(v as 'of'|'ratio')}><TabsList aria-label="Percentage calculation type"><TabsTrigger value="of">What is A% of B?</TabsTrigger><TabsTrigger value="ratio">A is what % of B?</TabsTrigger></TabsList><TabsContent value="of">{content}</TabsContent><TabsContent value="ratio">{content}</TabsContent></Tabs>;
}
function Fuel(){
 const[d,D]=useState('100'),[e,E]=useState('15'),[p,P]=useState(''),[people,S]=useState('1'),[currency,C]=useState('USD');
 const[du,DU]=useState<'km'|'mi'>('km'),[eu,EU]=useState<'km/L'|'L/100km'|'mpg'|'mpg-imp'>('km/L'),[pu,PU]=useState<'L'|'gal'|'gal-imp'>('L'),[region,Region]=useState('custom');
 const chooseRegion=(id:string)=>{Region(id);const r=fuelRegions.find(r=>r.id===id);if(r&&id!=='custom'){C(r.currency);DU(r.distance);EU(r.efficiency);PU(r.price);D('');E('');P('')}};
 let cost=0,litres=0,perPerson=0,error='';try{const r=journeyFuelCost(number(d),number(e),number(p),du,eu,pu,number(people));cost=r.cost;litres=r.litres;perPerson=r.costPerPerson}catch(err){error=(err as Error).message}
 const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency,currencyDisplay:'code'}).format(v);
 return <><div className="fuel-region-fields input-grid"><div><label className="field-label" htmlFor="fuel-region">Country / region</label><select id="fuel-region" className="field-input" value={region} onChange={ev=>chooseRegion(ev.target.value)}>{fuelRegions.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></div><div><label className="field-label" htmlFor="fuel-currency">Currency</label><select id="fuel-currency" className="field-input" value={currency} onChange={ev=>C(ev.target.value)}>{currencies.map(c=><option value={c} key={c}>{c} · {currencyNames.of(c)}</option>)}</select></div></div><p className="small-note fuel-region-note">Country selection sets suggested units and currency. Changing country clears numeric inputs; currency changes only the display label.</p><div className="input-grid"><Field label={`Trip distance (${du})`} value={d} onChange={D} min={0}/><div><label className="field-label" htmlFor="distance-unit">Distance unit</label><select className="field-input" id="distance-unit" value={du} onChange={ev=>DU(ev.target.value as typeof du)}><option value="km">Kilometres</option><option value="mi">Miles</option></select></div><Field label={`Fuel efficiency (${eu==='mpg'?'US mpg':eu==='mpg-imp'?'Imperial mpg':eu})`} value={e} onChange={E} min={0.1}/><div><label className="field-label" htmlFor="efficiency-unit">Efficiency unit</label><select className="field-input" id="efficiency-unit" value={eu} onChange={ev=>EU(ev.target.value as typeof eu)}><option value="km/L">Kilometres per litre</option><option value="L/100km">Litres per 100 km</option><option value="mpg">Miles per US gallon</option><option value="mpg-imp">Miles per Imperial gallon</option></select></div><Field label={`Fuel price per ${pu==='L'?'litre':pu==='gal'?'US gallon':'Imperial gallon'}`} value={p} onChange={P} min={0}/><div><label className="field-label" htmlFor="price-unit">Price unit</label><select className="field-input" id="price-unit" value={pu} onChange={ev=>PU(ev.target.value as typeof pu)}><option value="L">Per litre</option><option value="gal">Per US gallon</option><option value="gal-imp">Per Imperial gallon</option></select></div><Field label="People sharing the cost" value={people} onChange={S} min={1} max={10000}/></div><div className="result-panel"><output aria-live="polite" aria-atomic="true"><span className="result-label">Estimated journey cost</span>{error?<p className={p===''?'result-detail':'error-message'}>{p===''?'Enter your fuel price to see the estimate.':error}</p>:<><strong className="result-value">{money(cost)}</strong><div className="fuel-result-detail"><span><b>{format(litres)} L</b> Fuel needed</span><span><b>{money(perPerson)}</b> Per person</span></div></>}</output></div><p className="small-note">Fuel only. Uses your entered price. US gallon: 3.785411784 L; Imperial gallon: 4.54609 L. No location detection, live prices or currency conversion.</p></>
}
function GPA({cumulative}:{cumulative:boolean}){const[rows,R]=useState([{id:1,credits:cumulative?'18':'3',points:'3.5'},{id:2,credits:cumulative?'18':'3',points:'3.0'},{id:3,credits:cumulative?'15':'2',points:'4.0'}]);let value=0,credits=0,error='';try{({value,credits}=weightedAverage(rows.map(r=>({credits:number(r.credits),points:number(r.points)}))))}catch(e){error=(e as Error).message}const update=(id:number,key:string,v:string)=>R(previous=>previous.map(r=>r.id===id?{...r,[key]:v}:r));return <><div className="grade-table-head" aria-hidden="true"><span>{cumulative?'Semester':'Course'}</span><span>Credits</span><span>{cumulative?'GPA':'Grade points'}</span><span/></div>{rows.map((r,i)=><div className="grade-row" key={r.id}><span>{cumulative?'Sem.':'Course'} {i+1}</span><label className="grade-cell"><span>Credits</span><input className="field-input" inputMode="decimal" type="number" step="any" min="0.1" max="1000" aria-label={`${cumulative?'Semester':'Course'} ${i+1} credits`} value={r.credits} onChange={e=>update(r.id,'credits',e.target.value)}/></label><label className="grade-cell"><span>{cumulative?'GPA':'Grade points'}</span><input className="field-input" inputMode="decimal" type="number" step="any" min="0" max="10" aria-label={`${cumulative?'Semester':'Course'} ${i+1} ${cumulative?'GPA':'grade points'}`} value={r.points} onChange={e=>update(r.id,'points',e.target.value)}/></label><button className="remove-row" disabled={rows.length===1} aria-label={`Remove ${cumulative?'semester':'course'} ${i+1}`} onClick={()=>R(previous=>previous.filter(x=>x.id!==r.id))}><Trash2 size={14}/></button></div>)}<button className="outline-button" disabled={rows.length>=40} onClick={()=>{R(previous=>previous.length>=40?previous:[...previous,{id:Math.max(...previous.map(row=>row.id))+1,credits:cumulative?'18':'3',points:'0'}])}}><Plus size={14} style={{display:'inline',marginRight:6}}/>Add {cumulative?'semester':'course'}</button><div className="result-panel"><output aria-live="polite" aria-atomic="true"><span className="result-label">Your {cumulative?'CGPA':'semester GPA'}</span>{error?<p className="error-message">{error}</p>:<><strong className="result-value">{value.toFixed(2)}</strong><p className="result-detail">{credits} total credits · credit-weighted average</p></>}</output></div><p className="small-note">Sample values are provided to start. Replace them with your own grades. Use your university’s grade-point scale.</p></>}
